### ISSUE TITLE
Plugin v1.5.6 - unexpected return code (1) or response value

### ISSUE THREAD

**Issue by Les-Fleming** [4ch1m/intellij-ansible-lint#10]
Hello,

First off great work for taking the time and effort to create this plugin! 

I installed v1.5.6 in IntelliJ IDEA 2023.2.5 (Ultimate Edition) on macOS Sonoma 14.1.1. I also installed ansible-lint via brew and checking the version shows the following :
`ansible --version = ansible-lint 6.22.0 using ansible-core:2.15.6 ansible-compat:4.1.10 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8`

When I click the test button, I receive error - `unexpected return code (1) or response value`

Is there anything else I need to configure in order for the test to succeed?

<img width="439" alt="Screenshot 2023-11-14 at 16 19 59" src="https://github.com/4ch1m/intellij-ansible-lint/assets/95048020/5e7e7719-d34a-4310-8530-9a37d3d3fb4b">

Les

**Comment by Les-Fleming** [comment]
Apologies.. I only noticed the following in the README - Alternative installation methods (like [Poetry](https://python-poetry.org/), [Homebrew](https://brew.sh/), etc.) are also not supported.

Based on this statement, I can only presume that the order in which I have installed ansible-lint will not work with your plugin?

Les

**Comment by 4ch1m** [comment]
Hi there,

I neither use Mac, nor Homebrew... so I can't really help/assist here. Sorry.
However, this doesn't necessarily mean that it is impossible to get it running.

The thing is:
IntelliJ will invoke your binary/script (installed/set up via Homebrow) from its own context; possibly not being aware of your (Homebrew-)environment.
There's a `GeneralCommandLine`-object (provided by the IntelliJ/IDEA framework) which does the magic: https://github.com/4ch1m/intellij-ansible-lint/blob/de8f3975f983c128d3e8d1ccc86ea9c4e23fc507/src/main/kotlin/de/achimonline/ansible_lint/command/AnsibleLintCommandLine.kt#L11-L23

So... if your `ansible-lint` installation works from **ANY** "non-login" shell, then it should work here as well... I guess. :smile:

Anyway...
Why not try to install `ansible-lint` just the way described in the README?
It should work on Mac too.

**Comment by Les-Fleming** [comment]
Thanks very much for the info Achim. I will give it a whirl :).

**Comment by david-pili** [comment]
Sorry for the necro, I ran into a similar issue and ended up using pipx to solve it
## Pipx

Pipx can be used as an alternative to manually configuring a venv. It has the advantage of automatically adding the installed binaries to your path and allows specifying the ansible verion ansible-lint uses

* Install [Pipx](https://pipx.pypa.io/stable/)

* Install ansible with pipx (change 6.7.0 to your required version, or remove it to install the latest)
  ```
  pipx install --include-deps ansible==6.7.0
  ```

* Inject ansible-lint into the pipx ansible venv 
  ```
  pipx inject --include-deps ansible ansible-lint
  ```

`ansible` and `ansible-lint` should now be availible in your pathv
