### ISSUE TITLE
Exclude YAML file from linting with IntelliJ Ansible Lint

### ISSUE THREAD

**Issue by christoph-bessei** [4ch1m/intellij-ansible-lint#15]
# Issue

It seems that it's currently impossible to exclude a `*.yml` from linting with this plugin. Even if the file is added to `excluded_paths`, it will still be linted.

# Example

`.gitlab-ci.yml` is linted, even though it's part of `excluded_paths`:
![image](https://github.com/4ch1m/intellij-ansible-lint/assets/28066477/047760e5-731e-4387-9354-de546fa2b594)

![image](https://github.com/4ch1m/intellij-ansible-lint/assets/28066477/f138b968-1562-44a5-ab07-b7dbdc7783e5)

# Reproducion repository

https://github.com/christoph-bessei/intellij-ansible-lint-reproduction

# Possible reason

It seems that  `ansible-lint` ignores `excluded_paths`, if a filename is passed in the CLI:

![image](https://github.com/4ch1m/intellij-ansible-lint/assets/28066477/fea30405-0750-4bda-bc62-30eae4052b27)

Related (at least I think so) code line:  
https://github.com/ansible/ansible-lint/blob/36e2674032ccb6c5f610a1b683c9e8c0b5ec80ab/src/ansiblelint/runner.py#L135

# Solutions

I'm honestly not sure. Maybe parse `excluded_paths` and do not call `ansible-lint` for excluded files/directories?

**Comment by 4ch1m** [comment]
The `excluded_paths` option can be used to exclude **paths**; not **files** (check: [Ansible-lint configuration](https://ansible.readthedocs.io/projects/lint/configuring/#ansible-lint-configuration)).

You could use `.ansible-lint-ignore` to exclude certain rules/checks from specific files (see [Ignoring rules for entire files](https://ansible.readthedocs.io/projects/lint/configuring/#ignoring-rules-for-entire-files)).

Put this into a `.ansible-lint-ignore` file (adjacent to your config-file):
```
.gitlab-ci.yml yaml[brackets]
```

However, this would still mean that the file gets linted (but errors would not be marked/annotated as such).

**Comment by christoph-bessei** [comment]
Thanks for the quick answer! 

> The excluded_paths option can be used to exclude paths; not files (check: [Ansible-lint configuration](https://ansible.readthedocs.io/projects/lint/configuring/#ansible-lint-configuration)).

`excluded_paths` also works with files (at least for me).

With `.gitlab-ci.yml` in `ansible-lint.yml`:
![image](https://github.com/4ch1m/intellij-ansible-lint/assets/28066477/542e2025-59f6-4e1b-bbcb-ed24258b5d49)

Without `.gitlab-ci.yml` in `ansible-lint.yml`:
![image](https://github.com/4ch1m/intellij-ansible-lint/assets/28066477/b24032b4-2887-425a-81e1-4f84817e5706)

> You could use .ansible-lint-ignore to exclude certain rules/checks from specific files (see [Ignoring rules for entire files](https://ansible.readthedocs.io/projects/lint/configuring/#ignoring-rules-for-entire-files)).

Thanks for the hint, that's a great workaround! :slightly_smiling_face:
