### ISSUE TITLE
Impossible to use the plugin

### ISSUE THREAD

**Issue by florian-bellencontre** [4ch1m/intellij-ansible-lint#16]
Hello,

I followed the installation doc and everything seems ok in my configuration but I can't get ansible-lint to work in intellij.

![image](https://github.com/4ch1m/intellij-ansible-lint/assets/57491181/b1ce6e1a-becc-4fcd-afd8-671e089c7019)

I've tried looking in the logs but I can't see anything.

Do you have a way of debugging the problem?

Thank you

**Comment by 4ch1m** [comment]
As documented in the README file:

> By default, the plugin will only start linting YAML-files if your project root contains one of these [configuration files](https://ansible-lint.readthedocs.io/configuring/#using-local-configuration-files):
> 
>     .ansible-lint
>     .config/ansible-lint.yml
>

**Comment by florian-bellencontre** [comment]
The doc says we don't have to have this conf ifch afterwards:

> It is possible to use the plugin without a config file (see settings dialog above). However, this would mean that every YAML-file will unnecessarily be passed to ansible-lint; even in Non-Ansible projects.

Nevertheless, I tried with a rather basic ansible-lint conf file:
```
profile: production # min, basic, moderate,safety, shared, production
loop_var_prefix: "^(__|{role}_)"
var_naming_pattern: "^[a-z_][a-z0-9_]*$"
use_default_rules: true

enable_list:
  - yaml

offline: true

kinds:
  - yaml: "**/*.yaml-too"
```

If I run `~/ansible-lint/run.sh roles/XXXX` everything seems to work fine but I have nothing showing up in Intellij.

**Comment by 4ch1m** [comment]
Sorry; I'm afraid I can't help you fix your setup based on that information.

**Comment by florian-bellencontre** [comment]
What information can I give you to help me?

**Comment by florian-bellencontre** [comment]
Ok I just found it!

There's a conflict with this plugin: https://plugins.jetbrains.com/plugin/12626-orchide--ansible-language-support

As soon as I deactivate it, everything works perfectly. I'm not sure if I should also open an issue to the other plugin or if you have the means to solve this problem?

EDIT: 
Okay, this is how the Orchid plugin works : https://www.orchide.dev/pages/dokumentation#limitation-id

**Comment by 4ch1m** [comment]
> Ok I just found it!

:+1: 

> There's a conflict with this plugin: https://plugins.jetbrains.com/plugin/12626-orchide--ansible-language-support
> 
> As soon as I deactivate it, everything works perfectly. I'm not sure if I should also open an issue to the other plugin or if you have the means to solve this problem?

This plugin is not even open-source.
Sorry... but I neither have time nor interest to deal with it.

However, thanks for reporting back.
