### ISSUE TITLE
Ability to overwrite assumed project root directory

### ISSUE THREAD

**Issue by MPStudyly** [4ch1m/intellij-ansible-lint#19]
Hey, I might have overlooked this, but it seems that currently it is not possible to tell the linter which directory it should use as root directory for a project.

My use-case/problem is as follows: I have a project, which has the Ansible code lying in a sub directory of it's root. So right now I'm running into the issue that the linter is unable to find stuff (e.g. custom roles) lying in a custom directory. The additional search paths are defined in the ansible.cfg, but the linter doesn't pick it up, as it is not part of the project root.

As I've seen on other ansible-lint integration plugins (e.g. [vscode one](https://github.com/ansible/vscode-ansible/issues/885)), it should be possible to specify a project-dir via CLI, so it should just be a matter of exposing that argument to the Intellij conf and allowing it to be set per project (at least initially). In theory it must be settable per folder, as one could have multiple Ansible projects within a larger project, but I can imagine that getting very complex very fast :sweat_smile:

**Comment by 4ch1m** [comment]
Hi there,

the plugin assumes that your project-root is the actual root directory of the Ansible playbook.
Subdirectories are not supported at this point.

> it should be possible to specify a project-dir via CLI, so it should just be a matter of exposing that argument to the Intellij conf and allowing it to be set per project (at least initially).

I'm afraid it is not that simple.
The plugin provides live/instant linting of opened (Ansible-)YAML files.
Several "workarounds" are implemented to make this work internally (see [AnsibleLintTempEnv.kt](https://github.com/4ch1m/intellij-ansible-lint/blob/8558cd2e430410d42d849dd9911de3db93cf1345/src/main/kotlin/de/achimonline/ansible_lint/common/AnsibleLintTempEnv.kt)).

> ... but I can imagine that getting very complex very fast 😅

Exactly. :smile:
I don't think it's worth to raise complexity (of the project setup or the plugin's code) just for such a use-case.
I guess it would be easier to open your IDE in another window and start a new project with your sub-directory as root.

However, I'm open for improvements and reviewing pull-requests with new features. :grin:

**Comment by MPStudyly** [comment]
> I'm afraid it is not that simple. The plugin provides live/instant linting of opened (Ansible-)YAML files. Several "workarounds" are implemented to make this work internally (see [AnsibleLintTempEnv.kt](https://github.com/4ch1m/intellij-ansible-lint/blob/8558cd2e430410d42d849dd9911de3db93cf1345/src/main/kotlin/de/achimonline/ansible_lint/common/AnsibleLintTempEnv.kt)).

Dang it, bummer to hear that :/ I was aware of the temporary environment due to skimming over other issues and bits of code, I still hoped there could be a relatively simple way for some crude support.

Guess we'll have to change our workflow instead (at least for now). Thank you anyway! :)

> > ... but I can imagine that getting very complex very fast 😅
> 
> Exactly. 😄 I don't think it's worth to raise complexity (of the project setup or the plugin's code) just for such a use-case.

You could put some sort of poll in place to see how many users would be interested in this. I'm not expecting this becoming too relevant soon, but you never know if somebody appears and tries to tackle the problem just by seeing it being one ;)

> I guess it would be easier to open your IDE in another window and start a new project with your sub-directory as root.
>
> However, I'm open for improvements and reviewing pull-requests with new features. 😁

As you suggested and I stated above, I'm probably not going to be one of those trying to get it done, but adjusting my workflow instead :see_no_evil: Still, thanks for this awesome piece of software :)

**Comment by peternormann** [comment]
Sorry for adding to a closed issue, but I think you would prefer this over opening a new issue for the same use case.

I have the same problem as OP.

I was just wondering if it would be possible to use the `ANSIBLE_ROLES_PATH`, `ANSIBLE_INVENTORY`, and `ANSIBLE_CONFIG` environment variables, if set, and then fall back to the project root if not?

This is what I use with similar set up as OP.
