### ISSUE TITLE
Poetry support

### ISSUE THREAD

**Issue by gtirloni** [4ch1m/intellij-ansible-lint#2]
The plugin can't execute `ansible-lint` if it only exists inside the Poetry environment.

![image](https://user-images.githubusercontent.com/5902830/224567226-9c387c4b-7879-44c1-b54a-19f90d53813b.png)

Opening the console and running `ansible-lint` directly works because JetBrains loads the necessary environment config to enable the Poetry environment.

**Comment by ssbarnea** [comment]
Every time I see a poetry user, I have a muahahaha aha laugh,... It claims to provide a lot, but in practice it delivers other surprises, like https://github.com/ansible/ansible-lint/discussions/2820#discussioncomment-4400380 (unrelated to your problem). IMHO, that is a poetry support issue, unless this plugin claims to support poetry.

**Comment by 4ch1m** [comment]
Hi,

I'm not familiar with "Poetry"... and I'm not sure if I want to be. :smirk: 

This is completely out-of-scope of the plugin.

I've just updated the [README](https://github.com/4ch1m/intellij-ansible-lint#requirements) with a suggestion on how `ansible-lint` could/should be installed.

Hope this will provide help.

Thanks.

**Comment by gtirloni** [comment]
> IMHO, that is a poetry support issue, unless this plugin claims to support poetry.

Glad you prefixed with "IMHO" because a lot of people disagree with your humble opinion.
