### ISSUE TITLE
The temporary directory structure isn't handled properly on Windows (with WSL)

### ISSUE THREAD

**Issue by kolinger** [4ch1m/intellij-ansible-lint#22]
I face a issue with my workaround to make this plugin work on Windows, where ansible runs in WSL. The workaround works but I discovered unrelated issue based on this. As turned out it didn't have anything to do with the WSL part as I did originally suspected.

Only the playbook.yml reports all rule violations. The nested main.yml (in roles for example) report only basic yaml syntax violations. The underlying issue lies in the fact that the plugin prepares temporary directory but the main.yml from roles is incorrectly placed in root of the temp directory.

So I looked at the [AnsibleLintTempEnv](https://github.com/4ch1m/intellij-ansible-lint/blob/master/src/main/kotlin/de/achimonline/ansible_lint/common/AnsibleLintTempEnv.kt) class. Where I see the plugin doesn't expect that paths can have different directory separator. This works fine with Linux but won't work reliably on Windows since the Windows allows both slashes and backslashes. For one reason or another my IDE uses slashes for the virtualFile but backslashes in the projectBasePath thus the removePrefix() fails to do it's job since the prefix has different path separator than the subject.

Specifically removePrefix() returns full path with slashes, the split() splits on backslashes and thus returns 1 result since there are no backslashes and this result gets dropped by dropLast(1). Thus the result is always empty array of directories and that's why any file is always placed in root directory. I don't know how but the [removePrefix()](https://github.com/4ch1m/intellij-ansible-lint/blob/master/src/main/kotlin/de/achimonline/ansible_lint/common/AnsibleLintTempEnv.kt#L33) needs to normalize the paths somehow (realpath-like) before any string based operations happen.

<details>
<summary>Debugger</summary>

![image](https://github.com/user-attachments/assets/998677fb-d32c-45c3-8945-617212f63c8d)
</details>

[This WSL workaround works fine with this bug fixed](https://gist.github.com/kolinger/d13a86337b3d2d6881bd8bc57334f9eb).

As I understand this issue is not related to my setup. The virtual file system is using slashes regardless of the platform. Thus this likely makes this plugin unusable for any Windows machine.

The #23 fixes this issue, it's simple fix, but it wasn't easy to find this bug since I was debugging my setup and I was trying to fix something that wasn't broken first before I did give in to setup the environment for debugging the plugin itself.

**Comment by 4ch1m** [comment]
Version 1.9.0 of the plugin contains official/proper WSL support.
So this issue can be closed.
