### ISSUE TITLE
Support wsl on windows 

### ISSUE THREAD

**Issue by a-besson** [4ch1m/intellij-ansible-lint#3]
Hi,

Would that be possible to support ansible-lint command execution on WSL ? 

Thanks

**Comment by 4ch1m** [comment]
I don't know how if/how `ansible-lint` can be used with WSL.
Unfortunately  I don't have the setup/time/motivation to test it.

If it is "callable" from the command-line then it should work from within the plugin; I guess.

Any contributions in that regard are welcome though.

**Comment by NL9** [comment]
I can call `ansible-lint` from WSL using `wsl --shell-type login ansible-lint` command. Example:

```
$ wsl --shell-type login ansible-lint --version
ansible-lint 6.22.1 using ansible-core:2.16.2 ansible-compat:4.1.11 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8
```

Setting this command to plugin's command field give me `Unable to call Ansible Lint` error. Any ideas?

**Comment by 4ch1m** [comment]
@a-besson , @NL9 FYI: The plugin now officially supports WSL. You might want to try it out.
