### ISSUE TITLE
Role not found

### ISSUE THREAD

**Issue by targzeta** [4ch1m/intellij-ansible-lint#4]
Hi,
I have this tree:
```
/
|- ...
|- playbooks/
   |- my_playbook.yaml
   |- roles/
      |- my_role/
```
my_playbook.yaml:
```yaml
...
roles:
 - my_role
 ```

The plugins (not the command line tool `ansible-lint`) complains that:
`the role 'my_role' was not found in /tmp/[0-9]*/playbooks/roles:...`

The docs about roles says:
```
By default, Ansible looks for roles in the following locations:
    * in collections, if you are using them
    * ---> in a directory called roles/, relative to the playbook file <----
    * in the configured roles_path. The default search path is ~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles.
    * in the directory where the playbook file is located
```

Do you think that it's a bug?

Best regards and thanks for the great work,
Emanuele

Note: If I set the roles_path within the ansible.cfg, the warning goes away!

**Comment by 4ch1m** [comment]
> Do you think that it's a bug?

Not really a "bug"; but room for improvement. :smile: 

I've just prepared a [fix](https://github.com/4ch1m/intellij-ansible-lint/commit/17d75f0894bf5c9645a6e01a6b3b65b5a811d64d#diff-9b09db1ad9507c3d7ce7eb139f563e2c1e77d54f53eed42e142ea98d9861b5c0) that should solve this issue.

The new plugin version (`1.5.0`) should be available in the IntelliJ marketplace soon.

Please let me know if this solves the issues on your end as well.

Thanks for reporting!

**Comment by targzeta** [comment]
Hi,
the new version (1.5.0) solved the problem!

Thank you,
Emanuele
