### ISSUE TITLE
Unable to parse ansible-lint

### ISSUE THREAD

**Issue by elmuz** [4ch1m/intellij-ansible-lint#9]
I am on arch linux. OS provided version of ansible-lint is `6.22.0-2`. However, its actual printed version is:
```
$ ansible-lint --version
----
ansible-lint 7.dev0 using ansible-core:2.15.5 ansible-compat:4.1.10 ruamel-yaml:0.17.40 ruamel-yaml-clib:0.2.7
You are using a pre-release version of ansible-lint.
```
Can you handle this?

**Comment by 4ch1m** [comment]
> Can you handle this?

Yes, I can. :smile:

The dev-builds of _ansible-lint_ obviously don't use strict semver.
This should fix it: [de8f397](https://github.com/4ch1m/intellij-ansible-lint/commit/de8f3975f983c128d3e8d1ccc86ea9c4e23fc507)

Thanks for reporting!
